//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/google/gson/internal/bind/ArrayTypeAdapter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ArrayTypeAdapter")
#ifdef RESTRICT_ArrayTypeAdapter
#define INCLUDE_ALL_ArrayTypeAdapter 0
#else
#define INCLUDE_ALL_ArrayTypeAdapter 1
#endif
#undef RESTRICT_ArrayTypeAdapter

#if !defined (GSONArrayTypeAdapter_) && (INCLUDE_ALL_ArrayTypeAdapter || defined(INCLUDE_GSONArrayTypeAdapter))
#define GSONArrayTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_GSONTypeAdapter 1
#include "TypeAdapter.h"

@class GSONGson;
@class GSONJsonReader;
@class GSONJsonWriter;
@class IOSClass;
@protocol GSONTypeAdapterFactory;

/*!
 @brief Adapt an array of objects.
 */
@interface GSONArrayTypeAdapter : GSONTypeAdapter

#pragma mark Public

- (instancetype)initWithGSONGson:(GSONGson *)context
             withGSONTypeAdapter:(GSONTypeAdapter *)componentTypeAdapter
                    withIOSClass:(IOSClass *)componentType;

- (id)readWithGSONJsonReader:(GSONJsonReader *)inArg;

- (void)writeWithGSONJsonWriter:(GSONJsonWriter *)outArg
                         withId:(id)array;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(GSONArrayTypeAdapter)

inline id<GSONTypeAdapterFactory> GSONArrayTypeAdapter_get_FACTORY();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<GSONTypeAdapterFactory> GSONArrayTypeAdapter_FACTORY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(GSONArrayTypeAdapter, FACTORY, id<GSONTypeAdapterFactory>)

FOUNDATION_EXPORT void GSONArrayTypeAdapter_initWithGSONGson_withGSONTypeAdapter_withIOSClass_(GSONArrayTypeAdapter *self, GSONGson *context, GSONTypeAdapter *componentTypeAdapter, IOSClass *componentType);

FOUNDATION_EXPORT GSONArrayTypeAdapter *new_GSONArrayTypeAdapter_initWithGSONGson_withGSONTypeAdapter_withIOSClass_(GSONGson *context, GSONTypeAdapter *componentTypeAdapter, IOSClass *componentType) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GSONArrayTypeAdapter *create_GSONArrayTypeAdapter_initWithGSONGson_withGSONTypeAdapter_withIOSClass_(GSONGson *context, GSONTypeAdapter *componentTypeAdapter, IOSClass *componentType);

J2OBJC_TYPE_LITERAL_HEADER(GSONArrayTypeAdapter)

@compatibility_alias ComGoogleGsonInternalBindArrayTypeAdapter GSONArrayTypeAdapter;

#endif

#pragma pop_macro("INCLUDE_ALL_ArrayTypeAdapter")
