//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/google/gson/internal/Excluder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Excluder")
#ifdef RESTRICT_Excluder
#define INCLUDE_ALL_Excluder 0
#else
#define INCLUDE_ALL_Excluder 1
#endif
#undef RESTRICT_Excluder

#if !defined (GSONExcluder_) && (INCLUDE_ALL_Excluder || defined(INCLUDE_GSONExcluder))
#define GSONExcluder_

#define RESTRICT_TypeAdapterFactory 1
#define INCLUDE_GSONTypeAdapterFactory 1
#include "TypeAdapterFactory.h"

@class GSONGson;
@class GSONTypeAdapter;
@class GSONTypeToken;
@class IOSClass;
@class IOSIntArray;
@class JavaLangReflectField;
@protocol GSONExclusionStrategy;

/*!
 @brief This class selects which fields and types to omit.It is configurable,
  supporting version attributes <code>Since</code> and <code>Until</code>, modifiers,
  synthetic fields, anonymous and local classes, inner classes, and fields with
  the <code>Expose</code> annotation.
 <p>This class is a type adapter factory; types that are excluded will be
  adapted to null. It may delegate to another type adapter if only one
  direction is excluded.
 @author Joel Leitch
 @author Jesse Wilson
 */
@interface GSONExcluder : NSObject < GSONTypeAdapterFactory, NSCopying >

#pragma mark Public

- (instancetype)init;

- (GSONTypeAdapter *)createWithGSONGson:(GSONGson *)gson
                      withGSONTypeToken:(GSONTypeToken *)type;

- (GSONExcluder *)disableInnerClassSerialization;

- (jboolean)excludeClassWithIOSClass:(IOSClass *)clazz
                         withBoolean:(jboolean)serialize;

- (jboolean)excludeFieldWithJavaLangReflectField:(JavaLangReflectField *)field
                                     withBoolean:(jboolean)serialize;

- (GSONExcluder *)excludeFieldsWithoutExposeAnnotation;

- (GSONExcluder *)withExclusionStrategyWithGSONExclusionStrategy:(id<GSONExclusionStrategy>)exclusionStrategy
                                                     withBoolean:(jboolean)serialization
                                                     withBoolean:(jboolean)deserialization;

- (GSONExcluder *)withModifiersWithIntArray:(IOSIntArray *)modifiers;

- (GSONExcluder *)withVersionWithDouble:(jdouble)ignoreVersionsAfter;

#pragma mark Protected

- (GSONExcluder *)java_clone;

@end

J2OBJC_STATIC_INIT(GSONExcluder)

inline GSONExcluder *GSONExcluder_get_DEFAULT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT GSONExcluder *GSONExcluder_DEFAULT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(GSONExcluder, DEFAULT, GSONExcluder *)

FOUNDATION_EXPORT void GSONExcluder_init(GSONExcluder *self);

FOUNDATION_EXPORT GSONExcluder *new_GSONExcluder_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GSONExcluder *create_GSONExcluder_init();

J2OBJC_TYPE_LITERAL_HEADER(GSONExcluder)

@compatibility_alias ComGoogleGsonInternalExcluder GSONExcluder;

#endif

#pragma pop_macro("INCLUDE_ALL_Excluder")
