//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/github/howtobuildapp/libservice/execute/ExecuteInterface.java
//

#include "ExecuteInterface.h"
#include "J2ObjC_source.h"

@interface HTBAExecuteInterface : NSObject

@end

@implementation HTBAExecuteInterface

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 2, 3, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(executeRequestWithHTBARequest:withId:withHTBACallback:);
  methods[1].selector = @selector(cancelWithId:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "executeRequest", "LHTBARequest;LNSObject;LHTBACallback;", "cancel", "LNSObject;" };
  static const J2ObjcClassInfo _HTBAExecuteInterface = { "ExecuteInterface", "com.github.howtobuildapp.libservice.execute", ptrTable, methods, NULL, 7, 0x609, 2, 0, -1, -1, -1, -1, -1 };
  return &_HTBAExecuteInterface;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(HTBAExecuteInterface)
