//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/google/gson/FieldNamingPolicy.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_FieldNamingPolicy")
#ifdef RESTRICT_FieldNamingPolicy
#define INCLUDE_ALL_FieldNamingPolicy 0
#else
#define INCLUDE_ALL_FieldNamingPolicy 1
#endif
#undef RESTRICT_FieldNamingPolicy

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (GSONFieldNamingPolicy_) && (INCLUDE_ALL_FieldNamingPolicy || defined(INCLUDE_GSONFieldNamingPolicy))
#define GSONFieldNamingPolicy_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

#define RESTRICT_FieldNamingStrategy 1
#define INCLUDE_GSONFieldNamingStrategy 1
#include "FieldNamingStrategy.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, GSONFieldNamingPolicy_Enum) {
  GSONFieldNamingPolicy_Enum_IDENTITY = 0,
  GSONFieldNamingPolicy_Enum_UPPER_CAMEL_CASE = 1,
  GSONFieldNamingPolicy_Enum_UPPER_CAMEL_CASE_WITH_SPACES = 2,
  GSONFieldNamingPolicy_Enum_LOWER_CASE_WITH_UNDERSCORES = 3,
  GSONFieldNamingPolicy_Enum_LOWER_CASE_WITH_DASHES = 4,
  GSONFieldNamingPolicy_Enum_LOWER_CASE_WITH_DOTS = 5,
};

/*!
 @brief An enumeration that defines a few standard naming conventions for JSON field names.
 This enumeration should be used in conjunction with <code>com.google.gson.GsonBuilder</code>
  to configure a <code>com.google.gson.Gson</code> instance to properly translate Java field
  names into the desired JSON field names.
 @author Inderjeet Singh
 @author Joel Leitch
 */
@interface GSONFieldNamingPolicy : JavaLangEnum < GSONFieldNamingStrategy >

#pragma mark Public

+ (GSONFieldNamingPolicy *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

/*!
 @brief Converts the field name that uses camel-case define word separation into
  separate words that are separated by the provided <code>separatorString</code>.
 */
+ (NSString *)separateCamelCaseWithNSString:(NSString *)name
                               withNSString:(NSString *)separator;

/*!
 @brief Ensures the JSON field names begins with an upper case letter.
 */
+ (NSString *)upperCaseFirstLetterWithNSString:(NSString *)name;

@end

J2OBJC_STATIC_INIT(GSONFieldNamingPolicy)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT GSONFieldNamingPolicy *GSONFieldNamingPolicy_values_[];

/*!
 @brief Using this naming policy with Gson will ensure that the field name is
  unchanged.
 */
inline GSONFieldNamingPolicy *GSONFieldNamingPolicy_get_IDENTITY();
J2OBJC_ENUM_CONSTANT(GSONFieldNamingPolicy, IDENTITY)

/*!
 @brief Using this naming policy with Gson will ensure that the first "letter" of the Java
  field name is capitalized when serialized to its JSON form.
 <p>Here's a few examples of the form "Java Field Name" ---> "JSON Field Name":</p>
  <ul>
    <li>someFieldName ---> SomeFieldName</li>
    <li>_someFieldName ---> _SomeFieldName</li>
  </ul>
 */
inline GSONFieldNamingPolicy *GSONFieldNamingPolicy_get_UPPER_CAMEL_CASE();
J2OBJC_ENUM_CONSTANT(GSONFieldNamingPolicy, UPPER_CAMEL_CASE)

/*!
 @brief Using this naming policy with Gson will ensure that the first "letter" of the Java
  field name is capitalized when serialized to its JSON form and the words will be
  separated by a space.
 <p>Here's a few examples of the form "Java Field Name" ---> "JSON Field Name":</p>
  <ul>
    <li>someFieldName ---> Some Field Name</li>
    <li>_someFieldName ---> _Some Field Name</li>
  </ul>
 @since 1.4
 */
inline GSONFieldNamingPolicy *GSONFieldNamingPolicy_get_UPPER_CAMEL_CASE_WITH_SPACES();
J2OBJC_ENUM_CONSTANT(GSONFieldNamingPolicy, UPPER_CAMEL_CASE_WITH_SPACES)

/*!
 @brief Using this naming policy with Gson will modify the Java Field name from its camel cased
  form to a lower case field name where each word is separated by an underscore (_).
 <p>Here's a few examples of the form "Java Field Name" ---> "JSON Field Name":</p>
  <ul>
    <li>someFieldName ---> some_field_name</li>
    <li>_someFieldName ---> _some_field_name</li>
    <li>aStringField ---> a_string_field</li>
    <li>aURL ---> a_u_r_l</li>
  </ul>
 */
inline GSONFieldNamingPolicy *GSONFieldNamingPolicy_get_LOWER_CASE_WITH_UNDERSCORES();
J2OBJC_ENUM_CONSTANT(GSONFieldNamingPolicy, LOWER_CASE_WITH_UNDERSCORES)

/*!
 @brief Using this naming policy with Gson will modify the Java Field name from its camel cased
  form to a lower case field name where each word is separated by a dash (-).
 <p>Here's a few examples of the form "Java Field Name" ---> "JSON Field Name":</p>
  <ul>
    <li>someFieldName ---> some-field-name</li>
    <li>_someFieldName ---> _some-field-name</li>
    <li>aStringField ---> a-string-field</li>
    <li>aURL ---> a-u-r-l</li>
  </ul>
  Using dashes in JavaScript is not recommended since dash is also used for a minus sign in
  expressions. This requires that a field named with dashes is always accessed as a quoted
  property like <code>myobject['my-field']</code>. Accessing it as an object field 
 <code>myobject.my-field</code> will result in an unintended javascript expression.
 @since 1.4
 */
inline GSONFieldNamingPolicy *GSONFieldNamingPolicy_get_LOWER_CASE_WITH_DASHES();
J2OBJC_ENUM_CONSTANT(GSONFieldNamingPolicy, LOWER_CASE_WITH_DASHES)

/*!
 @brief Using this naming policy with Gson will modify the Java Field name from its camel cased
  form to a lower case field name where each word is separated by a dot (.).
 <p>Here's a few examples of the form "Java Field Name" ---> "JSON Field Name":</p>
  <ul>
    <li>someFieldName ---> some.field.name</li>
    <li>_someFieldName ---> _some.field.name</li>
    <li>aStringField ---> a.string.field</li>
    <li>aURL ---> a.u.r.l</li>
  </ul>
  Using dots in JavaScript is not recommended since dot is also used for a member sign in
  expressions. This requires that a field named with dots is always accessed as a quoted
  property like <code>myobject['my.field']</code>. Accessing it as an object field 
 <code>myobject.my.field</code> will result in an unintended javascript expression.
 @since 2.8
 */
inline GSONFieldNamingPolicy *GSONFieldNamingPolicy_get_LOWER_CASE_WITH_DOTS();
J2OBJC_ENUM_CONSTANT(GSONFieldNamingPolicy, LOWER_CASE_WITH_DOTS)

FOUNDATION_EXPORT NSString *GSONFieldNamingPolicy_separateCamelCaseWithNSString_withNSString_(NSString *name, NSString *separator);

FOUNDATION_EXPORT NSString *GSONFieldNamingPolicy_upperCaseFirstLetterWithNSString_(NSString *name);

FOUNDATION_EXPORT IOSObjectArray *GSONFieldNamingPolicy_values();

FOUNDATION_EXPORT GSONFieldNamingPolicy *GSONFieldNamingPolicy_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT GSONFieldNamingPolicy *GSONFieldNamingPolicy_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(GSONFieldNamingPolicy)

@compatibility_alias ComGoogleGsonFieldNamingPolicy GSONFieldNamingPolicy;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_FieldNamingPolicy")
