//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/google/gson/JsonDeserializationContext.java
//

#include "J2ObjC_source.h"
#include "JsonDeserializationContext.h"

@interface GSONJsonDeserializationContext : NSObject

@end

@implementation GSONJsonDeserializationContext

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSObject;", 0x401, 0, 1, 2, 3, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(deserializeWithGSONJsonElement:withJavaLangReflectType:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "deserialize", "LGSONJsonElement;LJavaLangReflectType;", "LGSONJsonParseException;", "<T:Ljava/lang/Object;>(Lcom/google/gson/JsonElement;Ljava/lang/reflect/Type;)TT;" };
  static const J2ObjcClassInfo _GSONJsonDeserializationContext = { "JsonDeserializationContext", "com.google.gson", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_GSONJsonDeserializationContext;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(GSONJsonDeserializationContext)
