//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/github/howtobuildapp/libservice/execute/JSONResponse.java
//

#include "J2ObjC_source.h"
#include "JSONResponse.h"
#include "JsonElement.h"
#include "Response.h"

@implementation HTBAJSONResponse

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  HTBAJSONResponse_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (GSONJsonElement *)getJsonResult {
  id ret = [super getResult];
  if (ret != nil && [ret isKindOfClass:[GSONJsonElement class]]) {
    return (GSONJsonElement *) cast_chk(ret, [GSONJsonElement class]);
  }
  return nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LGSONJsonElement;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getJsonResult);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _HTBAJSONResponse = { "JSONResponse", "com.github.howtobuildapp.libservice.execute", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_HTBAJSONResponse;
}

@end

void HTBAJSONResponse_init(HTBAJSONResponse *self) {
  HTBAResponse_init(self);
}

HTBAJSONResponse *new_HTBAJSONResponse_init() {
  J2OBJC_NEW_IMPL(HTBAJSONResponse, init)
}

HTBAJSONResponse *create_HTBAJSONResponse_init() {
  J2OBJC_CREATE_IMPL(HTBAJSONResponse, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(HTBAJSONResponse)
