//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/google/gson/JsonStreamParser.java
//

#include "J2ObjC_source.h"
#include "JsonElement.h"
#include "JsonIOException.h"
#include "JsonParseException.h"
#include "JsonReader.h"
#include "JsonStreamParser.h"
#include "JsonSyntaxException.h"
#include "JsonToken.h"
#include "MalformedJsonException.h"
#include "Streams.h"
#include "java/io/EOFException.h"
#include "java/io/IOException.h"
#include "java/io/Reader.h"
#include "java/io/StringReader.h"
#include "java/lang/OutOfMemoryError.h"
#include "java/lang/StackOverflowError.h"
#include "java/lang/Throwable.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/util/Iterator.h"
#include "java/util/NoSuchElementException.h"
#include "java/util/function/Consumer.h"

@interface GSONJsonStreamParser () {
 @public
  GSONJsonReader *parser_;
  id lock_;
}

@end

J2OBJC_FIELD_SETTER(GSONJsonStreamParser, parser_, GSONJsonReader *)
J2OBJC_FIELD_SETTER(GSONJsonStreamParser, lock_, id)

@implementation GSONJsonStreamParser

- (instancetype)initWithNSString:(NSString *)json {
  GSONJsonStreamParser_initWithNSString_(self, json);
  return self;
}

- (instancetype)initWithJavaIoReader:(JavaIoReader *)reader {
  GSONJsonStreamParser_initWithJavaIoReader_(self, reader);
  return self;
}

- (GSONJsonElement *)next {
  if (![self hasNext]) {
    @throw new_JavaUtilNoSuchElementException_init();
  }
  @try {
    return GSONStreams_parseWithGSONJsonReader_(parser_);
  }
  @catch (JavaLangStackOverflowError *e) {
    @throw new_GSONJsonParseException_initWithNSString_withJavaLangThrowable_(@"Failed parsing JSON source to Json", e);
  }
  @catch (JavaLangOutOfMemoryError *e) {
    @throw new_GSONJsonParseException_initWithNSString_withJavaLangThrowable_(@"Failed parsing JSON source to Json", e);
  }
  @catch (GSONJsonParseException *e) {
    @throw [[e getCause] isKindOfClass:[JavaIoEOFException class]] ? new_JavaUtilNoSuchElementException_init() : (id) e;
  }
}

- (jboolean)hasNext {
  @synchronized(lock_) {
    @try {
      return [((GSONJsonReader *) nil_chk(parser_)) peek] != JreLoadEnum(GSONJsonToken, END_DOCUMENT);
    }
    @catch (GSONMalformedJsonException *e) {
      @throw new_GSONJsonSyntaxException_initWithJavaLangThrowable_(e);
    }
    @catch (JavaIoIOException *e) {
      @throw new_GSONJsonIOException_initWithJavaLangThrowable_(e);
    }
  }
}

- (void)remove {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)forEachRemainingWithJavaUtilFunctionConsumer:(id<JavaUtilFunctionConsumer>)arg0 {
  JavaUtilIterator_forEachRemainingWithJavaUtilFunctionConsumer_(self, arg0);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, "LGSONJsonElement;", 0x1, -1, -1, 2, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:);
  methods[1].selector = @selector(initWithJavaIoReader:);
  methods[2].selector = @selector(next);
  methods[3].selector = @selector(hasNext);
  methods[4].selector = @selector(remove);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "parser_", "LGSONJsonReader;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "lock_", "LNSObject;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;", "LJavaIoReader;", "LGSONJsonParseException;", "Ljava/lang/Object;Ljava/util/Iterator<Lcom/google/gson/JsonElement;>;" };
  static const J2ObjcClassInfo _GSONJsonStreamParser = { "JsonStreamParser", "com.google.gson", ptrTable, methods, fields, 7, 0x11, 5, 2, -1, -1, -1, 3, -1 };
  return &_GSONJsonStreamParser;
}

@end

void GSONJsonStreamParser_initWithNSString_(GSONJsonStreamParser *self, NSString *json) {
  GSONJsonStreamParser_initWithJavaIoReader_(self, new_JavaIoStringReader_initWithNSString_(json));
}

GSONJsonStreamParser *new_GSONJsonStreamParser_initWithNSString_(NSString *json) {
  J2OBJC_NEW_IMPL(GSONJsonStreamParser, initWithNSString_, json)
}

GSONJsonStreamParser *create_GSONJsonStreamParser_initWithNSString_(NSString *json) {
  J2OBJC_CREATE_IMPL(GSONJsonStreamParser, initWithNSString_, json)
}

void GSONJsonStreamParser_initWithJavaIoReader_(GSONJsonStreamParser *self, JavaIoReader *reader) {
  NSObject_init(self);
  self->parser_ = new_GSONJsonReader_initWithJavaIoReader_(reader);
  [self->parser_ setLenientWithBoolean:true];
  self->lock_ = new_NSObject_init();
}

GSONJsonStreamParser *new_GSONJsonStreamParser_initWithJavaIoReader_(JavaIoReader *reader) {
  J2OBJC_NEW_IMPL(GSONJsonStreamParser, initWithJavaIoReader_, reader)
}

GSONJsonStreamParser *create_GSONJsonStreamParser_initWithJavaIoReader_(JavaIoReader *reader) {
  J2OBJC_CREATE_IMPL(GSONJsonStreamParser, initWithJavaIoReader_, reader)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(GSONJsonStreamParser)
