//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/google/gson/internal/JsonReaderInternalAccess.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonReaderInternalAccess")
#ifdef RESTRICT_JsonReaderInternalAccess
#define INCLUDE_ALL_JsonReaderInternalAccess 0
#else
#define INCLUDE_ALL_JsonReaderInternalAccess 1
#endif
#undef RESTRICT_JsonReaderInternalAccess

#if !defined (GSONJsonReaderInternalAccess_) && (INCLUDE_ALL_JsonReaderInternalAccess || defined(INCLUDE_GSONJsonReaderInternalAccess))
#define GSONJsonReaderInternalAccess_

@class GSONJsonReader;

/*!
 @brief Internal-only APIs of JsonReader available only to other classes in Gson.
 */
@interface GSONJsonReaderInternalAccess : NSObject

#pragma mark Public

- (instancetype)init;

/*!
 @brief Changes the type of the current property name token to a string value.
 */
- (void)promoteNameToValueWithGSONJsonReader:(GSONJsonReader *)reader;

@end

J2OBJC_EMPTY_STATIC_INIT(GSONJsonReaderInternalAccess)

inline GSONJsonReaderInternalAccess *GSONJsonReaderInternalAccess_get_INSTANCE();
inline GSONJsonReaderInternalAccess *GSONJsonReaderInternalAccess_set_INSTANCE(GSONJsonReaderInternalAccess *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT GSONJsonReaderInternalAccess *GSONJsonReaderInternalAccess_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ(GSONJsonReaderInternalAccess, INSTANCE, GSONJsonReaderInternalAccess *)

FOUNDATION_EXPORT void GSONJsonReaderInternalAccess_init(GSONJsonReaderInternalAccess *self);

J2OBJC_TYPE_LITERAL_HEADER(GSONJsonReaderInternalAccess)

@compatibility_alias ComGoogleGsonInternalJsonReaderInternalAccess GSONJsonReaderInternalAccess;

#endif

#pragma pop_macro("INCLUDE_ALL_JsonReaderInternalAccess")
