//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/google/gson/internal/bind/JsonTreeReader.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonTreeReader")
#ifdef RESTRICT_JsonTreeReader
#define INCLUDE_ALL_JsonTreeReader 0
#else
#define INCLUDE_ALL_JsonTreeReader 1
#endif
#undef RESTRICT_JsonTreeReader

#if !defined (GSONJsonTreeReader_) && (INCLUDE_ALL_JsonTreeReader || defined(INCLUDE_GSONJsonTreeReader))
#define GSONJsonTreeReader_

#define RESTRICT_JsonReader 1
#define INCLUDE_GSONJsonReader 1
#include "JsonReader.h"

@class GSONJsonElement;
@class GSONJsonToken;
@class JavaIoReader;

/*!
 @brief This reader walks the elements of a JsonElement as if it was coming from a
  character stream.
 @author Jesse Wilson
 */
@interface GSONJsonTreeReader : GSONJsonReader

#pragma mark Public

- (instancetype)initWithGSONJsonElement:(GSONJsonElement *)element;

- (void)beginArray;

- (void)beginObject;

- (void)close;

- (void)endArray;

- (void)endObject;

- (NSString *)getPath;

- (jboolean)hasNext;

- (jboolean)nextBoolean;

- (jdouble)nextDouble;

- (jint)nextInt;

- (jlong)nextLong;

- (NSString *)nextName;

- (void)nextNull;

- (NSString *)nextString;

- (GSONJsonToken *)peek;

- (void)promoteNameToValue;

- (void)skipValue;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithJavaIoReader:(JavaIoReader *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(GSONJsonTreeReader)

FOUNDATION_EXPORT void GSONJsonTreeReader_initWithGSONJsonElement_(GSONJsonTreeReader *self, GSONJsonElement *element);

FOUNDATION_EXPORT GSONJsonTreeReader *new_GSONJsonTreeReader_initWithGSONJsonElement_(GSONJsonElement *element) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GSONJsonTreeReader *create_GSONJsonTreeReader_initWithGSONJsonElement_(GSONJsonElement *element);

J2OBJC_TYPE_LITERAL_HEADER(GSONJsonTreeReader)

@compatibility_alias ComGoogleGsonInternalBindJsonTreeReader GSONJsonTreeReader;

#endif

#pragma pop_macro("INCLUDE_ALL_JsonTreeReader")
