//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/google/gson/JsonElement.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "JsonArray.h"
#include "JsonElement.h"
#include "JsonNull.h"
#include "JsonObject.h"
#include "JsonPrimitive.h"
#include "JsonWriter.h"
#include "Streams.h"
#include "java/io/IOException.h"
#include "java/io/StringWriter.h"
#include "java/lang/AssertionError.h"
#include "java/lang/Deprecated.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/lang/annotation/Annotation.h"
#include "java/math/BigDecimal.h"
#include "java/math/BigInteger.h"

__attribute__((unused)) static IOSObjectArray *GSONJsonElement__Annotations$0();

@implementation GSONJsonElement

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  GSONJsonElement_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (GSONJsonElement *)deepCopy {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (jboolean)isJsonArray {
  return [self isKindOfClass:[GSONJsonArray class]];
}

- (jboolean)isJsonObject {
  return [self isKindOfClass:[GSONJsonObject class]];
}

- (jboolean)isJsonPrimitive {
  return [self isKindOfClass:[GSONJsonPrimitive class]];
}

- (jboolean)isJsonNull {
  return [self isKindOfClass:[GSONJsonNull class]];
}

- (GSONJsonObject *)getAsJsonObject {
  if ([self isJsonObject]) {
    return (GSONJsonObject *) cast_chk(self, [GSONJsonObject class]);
  }
  @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@", @"Not a JSON Object: ", self));
}

- (GSONJsonArray *)getAsJsonArray {
  if ([self isJsonArray]) {
    return (GSONJsonArray *) cast_chk(self, [GSONJsonArray class]);
  }
  @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@", @"Not a JSON Array: ", self));
}

- (GSONJsonPrimitive *)getAsJsonPrimitive {
  if ([self isJsonPrimitive]) {
    return (GSONJsonPrimitive *) cast_chk(self, [GSONJsonPrimitive class]);
  }
  @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@", @"Not a JSON Primitive: ", self));
}

- (GSONJsonNull *)getAsJsonNull {
  if ([self isJsonNull]) {
    return (GSONJsonNull *) cast_chk(self, [GSONJsonNull class]);
  }
  @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@", @"Not a JSON Null: ", self));
}

- (jboolean)getAsBoolean {
  @throw new_JavaLangUnsupportedOperationException_initWithNSString_([[self java_getClass] getSimpleName]);
}

- (NSNumber *)getAsNumber {
  @throw new_JavaLangUnsupportedOperationException_initWithNSString_([[self java_getClass] getSimpleName]);
}

- (NSString *)getAsString {
  @throw new_JavaLangUnsupportedOperationException_initWithNSString_([[self java_getClass] getSimpleName]);
}

- (jdouble)getAsDouble {
  @throw new_JavaLangUnsupportedOperationException_initWithNSString_([[self java_getClass] getSimpleName]);
}

- (jfloat)getAsFloat {
  @throw new_JavaLangUnsupportedOperationException_initWithNSString_([[self java_getClass] getSimpleName]);
}

- (jlong)getAsLong {
  @throw new_JavaLangUnsupportedOperationException_initWithNSString_([[self java_getClass] getSimpleName]);
}

- (jint)getAsInt {
  @throw new_JavaLangUnsupportedOperationException_initWithNSString_([[self java_getClass] getSimpleName]);
}

- (jbyte)getAsByte {
  @throw new_JavaLangUnsupportedOperationException_initWithNSString_([[self java_getClass] getSimpleName]);
}

- (jchar)getAsCharacter {
  @throw new_JavaLangUnsupportedOperationException_initWithNSString_([[self java_getClass] getSimpleName]);
}

- (JavaMathBigDecimal *)getAsBigDecimal {
  @throw new_JavaLangUnsupportedOperationException_initWithNSString_([[self java_getClass] getSimpleName]);
}

- (JavaMathBigInteger *)getAsBigInteger {
  @throw new_JavaLangUnsupportedOperationException_initWithNSString_([[self java_getClass] getSimpleName]);
}

- (jshort)getAsShort {
  @throw new_JavaLangUnsupportedOperationException_initWithNSString_([[self java_getClass] getSimpleName]);
}

- (NSString *)description {
  @try {
    JavaIoStringWriter *stringWriter = new_JavaIoStringWriter_init();
    GSONJsonWriter *jsonWriter = new_GSONJsonWriter_initWithJavaIoWriter_(stringWriter);
    [jsonWriter setLenientWithBoolean:true];
    GSONStreams_writeWithGSONJsonElement_withGSONJsonWriter_(self, jsonWriter);
    return [stringWriter description];
  }
  @catch (JavaIoIOException *e) {
    @throw new_JavaLangAssertionError_initWithId_(e);
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LGSONJsonElement;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LGSONJsonObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LGSONJsonArray;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LGSONJsonPrimitive;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LGSONJsonNull;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSNumber;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "D", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "F", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "J", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "B", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "C", 0x1, -1, -1, -1, -1, 0, -1 },
    { NULL, "LJavaMathBigDecimal;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaMathBigInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "S", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(deepCopy);
  methods[2].selector = @selector(isJsonArray);
  methods[3].selector = @selector(isJsonObject);
  methods[4].selector = @selector(isJsonPrimitive);
  methods[5].selector = @selector(isJsonNull);
  methods[6].selector = @selector(getAsJsonObject);
  methods[7].selector = @selector(getAsJsonArray);
  methods[8].selector = @selector(getAsJsonPrimitive);
  methods[9].selector = @selector(getAsJsonNull);
  methods[10].selector = @selector(getAsBoolean);
  methods[11].selector = @selector(getAsNumber);
  methods[12].selector = @selector(getAsString);
  methods[13].selector = @selector(getAsDouble);
  methods[14].selector = @selector(getAsFloat);
  methods[15].selector = @selector(getAsLong);
  methods[16].selector = @selector(getAsInt);
  methods[17].selector = @selector(getAsByte);
  methods[18].selector = @selector(getAsCharacter);
  methods[19].selector = @selector(getAsBigDecimal);
  methods[20].selector = @selector(getAsBigInteger);
  methods[21].selector = @selector(getAsShort);
  methods[22].selector = @selector(description);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { (void *)&GSONJsonElement__Annotations$0, "toString" };
  static const J2ObjcClassInfo _GSONJsonElement = { "JsonElement", "com.google.gson", ptrTable, methods, NULL, 7, 0x401, 23, 0, -1, -1, -1, -1, -1 };
  return &_GSONJsonElement;
}

@end

void GSONJsonElement_init(GSONJsonElement *self) {
  NSObject_init(self);
}

IOSObjectArray *GSONJsonElement__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(GSONJsonElement)
