//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/google/gson/JsonParseException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonParseException")
#ifdef RESTRICT_JsonParseException
#define INCLUDE_ALL_JsonParseException 0
#else
#define INCLUDE_ALL_JsonParseException 1
#endif
#undef RESTRICT_JsonParseException

#if !defined (GSONJsonParseException_) && (INCLUDE_ALL_JsonParseException || defined(INCLUDE_GSONJsonParseException))
#define GSONJsonParseException_

#define RESTRICT_JavaLangRuntimeException 1
#define INCLUDE_JavaLangRuntimeException 1
#include "java/lang/RuntimeException.h"

@class JavaLangThrowable;

/*!
 @brief This exception is raised if there is a serious issue that occurs during parsing of a Json
  string.One of the main usages for this class is for the Gson infrastructure.
 If the incoming
  Json is bad/malicious, an instance of this exception is raised. 
 <p>This exception is a <code>RuntimeException</code> because it is exposed to the client. Using a 
 <code>RuntimeException</code> avoids bad coding practices on the client side where they catch the
  exception and do nothing. It is often the case that you want to blow up if there is a parsing
  error (i.e. often clients do not know how to recover from a <code>JsonParseException</code>.</p>
 @author Inderjeet Singh
 @author Joel Leitch
 */
@interface GSONJsonParseException : JavaLangRuntimeException

#pragma mark Public

/*!
 @brief Creates exception with the specified message.If you are wrapping another exception, consider
  using <code>Throwable)</code> instead.
 @param msg error message describing a possible cause of this exception.
 */
- (instancetype)initWithNSString:(NSString *)msg;

/*!
 @brief Creates exception with the specified message and cause.
 @param msg error message describing what happened.
 @param cause root exception that caused this exception to be thrown.
 */
- (instancetype)initWithNSString:(NSString *)msg
           withJavaLangThrowable:(JavaLangThrowable *)cause;

/*!
 @brief Creates exception with the specified cause.Consider using 
 <code>Throwable)</code> instead if you can describe what happened.
 @param cause root exception that caused this exception to be thrown.
 */
- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)cause;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1
                     withBoolean:(jboolean)arg2
                     withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(GSONJsonParseException)

inline jlong GSONJsonParseException_get_serialVersionUID();
#define GSONJsonParseException_serialVersionUID -4086729973971783390LL
J2OBJC_STATIC_FIELD_CONSTANT(GSONJsonParseException, serialVersionUID, jlong)

FOUNDATION_EXPORT void GSONJsonParseException_initWithNSString_(GSONJsonParseException *self, NSString *msg);

FOUNDATION_EXPORT GSONJsonParseException *new_GSONJsonParseException_initWithNSString_(NSString *msg) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GSONJsonParseException *create_GSONJsonParseException_initWithNSString_(NSString *msg);

FOUNDATION_EXPORT void GSONJsonParseException_initWithNSString_withJavaLangThrowable_(GSONJsonParseException *self, NSString *msg, JavaLangThrowable *cause);

FOUNDATION_EXPORT GSONJsonParseException *new_GSONJsonParseException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *cause) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GSONJsonParseException *create_GSONJsonParseException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *cause);

FOUNDATION_EXPORT void GSONJsonParseException_initWithJavaLangThrowable_(GSONJsonParseException *self, JavaLangThrowable *cause);

FOUNDATION_EXPORT GSONJsonParseException *new_GSONJsonParseException_initWithJavaLangThrowable_(JavaLangThrowable *cause) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GSONJsonParseException *create_GSONJsonParseException_initWithJavaLangThrowable_(JavaLangThrowable *cause);

J2OBJC_TYPE_LITERAL_HEADER(GSONJsonParseException)

@compatibility_alias ComGoogleGsonJsonParseException GSONJsonParseException;

#endif

#pragma pop_macro("INCLUDE_ALL_JsonParseException")
