//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/google/gson/internal/bind/JsonAdapterAnnotationTypeAdapterFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonAdapterAnnotationTypeAdapterFactory")
#ifdef RESTRICT_JsonAdapterAnnotationTypeAdapterFactory
#define INCLUDE_ALL_JsonAdapterAnnotationTypeAdapterFactory 0
#else
#define INCLUDE_ALL_JsonAdapterAnnotationTypeAdapterFactory 1
#endif
#undef RESTRICT_JsonAdapterAnnotationTypeAdapterFactory

#if !defined (GSONJsonAdapterAnnotationTypeAdapterFactory_) && (INCLUDE_ALL_JsonAdapterAnnotationTypeAdapterFactory || defined(INCLUDE_GSONJsonAdapterAnnotationTypeAdapterFactory))
#define GSONJsonAdapterAnnotationTypeAdapterFactory_

#define RESTRICT_TypeAdapterFactory 1
#define INCLUDE_GSONTypeAdapterFactory 1
#include "TypeAdapterFactory.h"

@class GSONConstructorConstructor;
@class GSONGson;
@class GSONTypeAdapter;
@class GSONTypeToken;
@protocol GSONJsonAdapter;

/*!
 @brief Given a type T, looks for the annotation <code>JsonAdapter</code> and uses an instance of the
  specified class as the default type adapter.
 @since 2.3
 */
@interface GSONJsonAdapterAnnotationTypeAdapterFactory : NSObject < GSONTypeAdapterFactory >

#pragma mark Public

- (instancetype)initWithGSONConstructorConstructor:(GSONConstructorConstructor *)constructorConstructor;

- (GSONTypeAdapter *)createWithGSONGson:(GSONGson *)gson
                      withGSONTypeToken:(GSONTypeToken *)targetType;

#pragma mark Package-Private

- (GSONTypeAdapter *)getTypeAdapterWithGSONConstructorConstructor:(GSONConstructorConstructor *)constructorConstructor
                                                     withGSONGson:(GSONGson *)gson
                                                withGSONTypeToken:(GSONTypeToken *)type
                                              withGSONJsonAdapter:(id<GSONJsonAdapter>)annotation;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(GSONJsonAdapterAnnotationTypeAdapterFactory)

FOUNDATION_EXPORT void GSONJsonAdapterAnnotationTypeAdapterFactory_initWithGSONConstructorConstructor_(GSONJsonAdapterAnnotationTypeAdapterFactory *self, GSONConstructorConstructor *constructorConstructor);

FOUNDATION_EXPORT GSONJsonAdapterAnnotationTypeAdapterFactory *new_GSONJsonAdapterAnnotationTypeAdapterFactory_initWithGSONConstructorConstructor_(GSONConstructorConstructor *constructorConstructor) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GSONJsonAdapterAnnotationTypeAdapterFactory *create_GSONJsonAdapterAnnotationTypeAdapterFactory_initWithGSONConstructorConstructor_(GSONConstructorConstructor *constructorConstructor);

J2OBJC_TYPE_LITERAL_HEADER(GSONJsonAdapterAnnotationTypeAdapterFactory)

@compatibility_alias ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory GSONJsonAdapterAnnotationTypeAdapterFactory;

#endif

#pragma pop_macro("INCLUDE_ALL_JsonAdapterAnnotationTypeAdapterFactory")
