//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/google/gson/LongSerializationPolicy.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "JsonElement.h"
#include "JsonPrimitive.h"
#include "LongSerializationPolicy.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Long.h"

__attribute__((unused)) static void GSONLongSerializationPolicy_initWithNSString_withInt_(GSONLongSerializationPolicy *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static GSONLongSerializationPolicy *new_GSONLongSerializationPolicy_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

@interface GSONLongSerializationPolicy_1 : GSONLongSerializationPolicy

- (GSONJsonElement *)serializeWithJavaLangLong:(JavaLangLong *)value;

@end

J2OBJC_EMPTY_STATIC_INIT(GSONLongSerializationPolicy_1)

__attribute__((unused)) static void GSONLongSerializationPolicy_1_initWithNSString_withInt_(GSONLongSerializationPolicy_1 *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static GSONLongSerializationPolicy_1 *new_GSONLongSerializationPolicy_1_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

@interface GSONLongSerializationPolicy_2 : GSONLongSerializationPolicy

- (GSONJsonElement *)serializeWithJavaLangLong:(JavaLangLong *)value;

@end

J2OBJC_EMPTY_STATIC_INIT(GSONLongSerializationPolicy_2)

__attribute__((unused)) static void GSONLongSerializationPolicy_2_initWithNSString_withInt_(GSONLongSerializationPolicy_2 *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static GSONLongSerializationPolicy_2 *new_GSONLongSerializationPolicy_2_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

J2OBJC_INITIALIZED_DEFN(GSONLongSerializationPolicy)

GSONLongSerializationPolicy *GSONLongSerializationPolicy_values_[2];

@implementation GSONLongSerializationPolicy

- (GSONJsonElement *)serializeWithJavaLangLong:(JavaLangLong *)value {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

+ (IOSObjectArray *)values {
  return GSONLongSerializationPolicy_values();
}

+ (GSONLongSerializationPolicy *)valueOfWithNSString:(NSString *)name {
  return GSONLongSerializationPolicy_valueOfWithNSString_(name);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LGSONJsonElement;", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "[LGSONLongSerializationPolicy;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LGSONLongSerializationPolicy;", 0x9, 2, 3, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(serializeWithJavaLangLong:);
  methods[1].selector = @selector(values);
  methods[2].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "DEFAULT", "LGSONLongSerializationPolicy;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "STRING", "LGSONLongSerializationPolicy;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
  };
  static const void *ptrTable[] = { "serialize", "LJavaLangLong;", "valueOf", "LNSString;", &JreEnum(GSONLongSerializationPolicy, DEFAULT), &JreEnum(GSONLongSerializationPolicy, STRING), "Ljava/lang/Enum<Lcom/google/gson/LongSerializationPolicy;>;" };
  static const J2ObjcClassInfo _GSONLongSerializationPolicy = { "LongSerializationPolicy", "com.google.gson", ptrTable, methods, fields, 7, 0x4401, 3, 2, -1, -1, -1, 6, -1 };
  return &_GSONLongSerializationPolicy;
}

+ (void)initialize {
  if (self == [GSONLongSerializationPolicy class]) {
    JreEnum(GSONLongSerializationPolicy, DEFAULT) = new_GSONLongSerializationPolicy_1_initWithNSString_withInt_(@"", 0);
    JreEnum(GSONLongSerializationPolicy, STRING) = new_GSONLongSerializationPolicy_2_initWithNSString_withInt_(@"", 1);
    J2OBJC_SET_INITIALIZED(GSONLongSerializationPolicy)
  }
}

@end

void GSONLongSerializationPolicy_initWithNSString_withInt_(GSONLongSerializationPolicy *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

GSONLongSerializationPolicy *new_GSONLongSerializationPolicy_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  J2OBJC_NEW_IMPL(GSONLongSerializationPolicy, initWithNSString_withInt_, __name, __ordinal)
}

IOSObjectArray *GSONLongSerializationPolicy_values() {
  GSONLongSerializationPolicy_initialize();
  return [IOSObjectArray arrayWithObjects:GSONLongSerializationPolicy_values_ count:2 type:GSONLongSerializationPolicy_class_()];
}

GSONLongSerializationPolicy *GSONLongSerializationPolicy_valueOfWithNSString_(NSString *name) {
  GSONLongSerializationPolicy_initialize();
  for (int i = 0; i < 2; i++) {
    GSONLongSerializationPolicy *e = GSONLongSerializationPolicy_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

GSONLongSerializationPolicy *GSONLongSerializationPolicy_fromOrdinal(NSUInteger ordinal) {
  GSONLongSerializationPolicy_initialize();
  if (ordinal >= 2) {
    return nil;
  }
  return GSONLongSerializationPolicy_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(GSONLongSerializationPolicy)

@implementation GSONLongSerializationPolicy_1

- (GSONJsonElement *)serializeWithJavaLangLong:(JavaLangLong *)value {
  return new_GSONJsonPrimitive_initWithNSNumber_(value);
}

- (void)dealloc {
  JreCheckFinalize(self, [GSONLongSerializationPolicy_1 class]);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LGSONJsonElement;", 0x1, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(serializeWithJavaLangLong:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "serialize", "LJavaLangLong;", "LGSONLongSerializationPolicy;" };
  static const J2ObjcClassInfo _GSONLongSerializationPolicy_1 = { "", "com.google.gson", ptrTable, methods, NULL, 7, 0xc018, 1, 0, 2, -1, -1, -1, -1 };
  return &_GSONLongSerializationPolicy_1;
}

@end

void GSONLongSerializationPolicy_1_initWithNSString_withInt_(GSONLongSerializationPolicy_1 *self, NSString *__name, jint __ordinal) {
  GSONLongSerializationPolicy_initWithNSString_withInt_(self, __name, __ordinal);
}

GSONLongSerializationPolicy_1 *new_GSONLongSerializationPolicy_1_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  J2OBJC_NEW_IMPL(GSONLongSerializationPolicy_1, initWithNSString_withInt_, __name, __ordinal)
}

@implementation GSONLongSerializationPolicy_2

- (GSONJsonElement *)serializeWithJavaLangLong:(JavaLangLong *)value {
  return new_GSONJsonPrimitive_initWithNSString_(NSString_java_valueOf_(value));
}

- (void)dealloc {
  JreCheckFinalize(self, [GSONLongSerializationPolicy_2 class]);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LGSONJsonElement;", 0x1, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(serializeWithJavaLangLong:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "serialize", "LJavaLangLong;", "LGSONLongSerializationPolicy;" };
  static const J2ObjcClassInfo _GSONLongSerializationPolicy_2 = { "", "com.google.gson", ptrTable, methods, NULL, 7, 0xc018, 1, 0, 2, -1, -1, -1, -1 };
  return &_GSONLongSerializationPolicy_2;
}

@end

void GSONLongSerializationPolicy_2_initWithNSString_withInt_(GSONLongSerializationPolicy_2 *self, NSString *__name, jint __ordinal) {
  GSONLongSerializationPolicy_initWithNSString_withInt_(self, __name, __ordinal);
}

GSONLongSerializationPolicy_2 *new_GSONLongSerializationPolicy_2_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  J2OBJC_NEW_IMPL(GSONLongSerializationPolicy_2, initWithNSString_withInt_, __name, __ordinal)
}
