//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/google/gson/stream/MalformedJsonException.java
//

#include "J2ObjC_source.h"
#include "MalformedJsonException.h"
#include "java/io/IOException.h"
#include "java/lang/Throwable.h"

inline jlong GSONMalformedJsonException_get_serialVersionUID();
#define GSONMalformedJsonException_serialVersionUID 1LL
J2OBJC_STATIC_FIELD_CONSTANT(GSONMalformedJsonException, serialVersionUID, jlong)

@implementation GSONMalformedJsonException

- (instancetype)initWithNSString:(NSString *)msg {
  GSONMalformedJsonException_initWithNSString_(self, msg);
  return self;
}

- (instancetype)initWithNSString:(NSString *)msg
           withJavaLangThrowable:(JavaLangThrowable *)throwable {
  GSONMalformedJsonException_initWithNSString_withJavaLangThrowable_(self, msg, throwable);
  return self;
}

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)throwable {
  GSONMalformedJsonException_initWithJavaLangThrowable_(self, throwable);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:);
  methods[1].selector = @selector(initWithNSString:withJavaLangThrowable:);
  methods[2].selector = @selector(initWithJavaLangThrowable:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = GSONMalformedJsonException_serialVersionUID, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;", "LNSString;LJavaLangThrowable;", "LJavaLangThrowable;" };
  static const J2ObjcClassInfo _GSONMalformedJsonException = { "MalformedJsonException", "com.google.gson.stream", ptrTable, methods, fields, 7, 0x11, 3, 1, -1, -1, -1, -1, -1 };
  return &_GSONMalformedJsonException;
}

@end

void GSONMalformedJsonException_initWithNSString_(GSONMalformedJsonException *self, NSString *msg) {
  JavaIoIOException_initWithNSString_(self, msg);
}

GSONMalformedJsonException *new_GSONMalformedJsonException_initWithNSString_(NSString *msg) {
  J2OBJC_NEW_IMPL(GSONMalformedJsonException, initWithNSString_, msg)
}

GSONMalformedJsonException *create_GSONMalformedJsonException_initWithNSString_(NSString *msg) {
  J2OBJC_CREATE_IMPL(GSONMalformedJsonException, initWithNSString_, msg)
}

void GSONMalformedJsonException_initWithNSString_withJavaLangThrowable_(GSONMalformedJsonException *self, NSString *msg, JavaLangThrowable *throwable) {
  JavaIoIOException_initWithNSString_(self, msg);
  (void) [self initCauseWithJavaLangThrowable:throwable];
}

GSONMalformedJsonException *new_GSONMalformedJsonException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *throwable) {
  J2OBJC_NEW_IMPL(GSONMalformedJsonException, initWithNSString_withJavaLangThrowable_, msg, throwable)
}

GSONMalformedJsonException *create_GSONMalformedJsonException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *throwable) {
  J2OBJC_CREATE_IMPL(GSONMalformedJsonException, initWithNSString_withJavaLangThrowable_, msg, throwable)
}

void GSONMalformedJsonException_initWithJavaLangThrowable_(GSONMalformedJsonException *self, JavaLangThrowable *throwable) {
  JavaIoIOException_init(self);
  (void) [self initCauseWithJavaLangThrowable:throwable];
}

GSONMalformedJsonException *new_GSONMalformedJsonException_initWithJavaLangThrowable_(JavaLangThrowable *throwable) {
  J2OBJC_NEW_IMPL(GSONMalformedJsonException, initWithJavaLangThrowable_, throwable)
}

GSONMalformedJsonException *create_GSONMalformedJsonException_initWithJavaLangThrowable_(JavaLangThrowable *throwable) {
  J2OBJC_CREATE_IMPL(GSONMalformedJsonException, initWithJavaLangThrowable_, throwable)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(GSONMalformedJsonException)
