//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/google/gson/stream/MalformedJsonException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_MalformedJsonException")
#ifdef RESTRICT_MalformedJsonException
#define INCLUDE_ALL_MalformedJsonException 0
#else
#define INCLUDE_ALL_MalformedJsonException 1
#endif
#undef RESTRICT_MalformedJsonException

#if !defined (GSONMalformedJsonException_) && (INCLUDE_ALL_MalformedJsonException || defined(INCLUDE_GSONMalformedJsonException))
#define GSONMalformedJsonException_

#define RESTRICT_JavaIoIOException 1
#define INCLUDE_JavaIoIOException 1
#include "java/io/IOException.h"

@class JavaLangThrowable;

/*!
 @brief Thrown when a reader encounters malformed JSON.Some syntax errors can be
  ignored by calling <code>JsonReader.setLenient(boolean)</code>.
 */
@interface GSONMalformedJsonException : JavaIoIOException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)initWithNSString:(NSString *)msg
           withJavaLangThrowable:(JavaLangThrowable *)throwable;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)throwable;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(GSONMalformedJsonException)

FOUNDATION_EXPORT void GSONMalformedJsonException_initWithNSString_(GSONMalformedJsonException *self, NSString *msg);

FOUNDATION_EXPORT GSONMalformedJsonException *new_GSONMalformedJsonException_initWithNSString_(NSString *msg) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GSONMalformedJsonException *create_GSONMalformedJsonException_initWithNSString_(NSString *msg);

FOUNDATION_EXPORT void GSONMalformedJsonException_initWithNSString_withJavaLangThrowable_(GSONMalformedJsonException *self, NSString *msg, JavaLangThrowable *throwable);

FOUNDATION_EXPORT GSONMalformedJsonException *new_GSONMalformedJsonException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *throwable) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GSONMalformedJsonException *create_GSONMalformedJsonException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *throwable);

FOUNDATION_EXPORT void GSONMalformedJsonException_initWithJavaLangThrowable_(GSONMalformedJsonException *self, JavaLangThrowable *throwable);

FOUNDATION_EXPORT GSONMalformedJsonException *new_GSONMalformedJsonException_initWithJavaLangThrowable_(JavaLangThrowable *throwable) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GSONMalformedJsonException *create_GSONMalformedJsonException_initWithJavaLangThrowable_(JavaLangThrowable *throwable);

J2OBJC_TYPE_LITERAL_HEADER(GSONMalformedJsonException)

@compatibility_alias ComGoogleGsonStreamMalformedJsonException GSONMalformedJsonException;

#endif

#pragma pop_macro("INCLUDE_ALL_MalformedJsonException")
