//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/github/howtobuildapp/libservice/platform/NotificationManager.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NotificationManager")
#ifdef RESTRICT_NotificationManager
#define INCLUDE_ALL_NotificationManager 0
#else
#define INCLUDE_ALL_NotificationManager 1
#endif
#undef RESTRICT_NotificationManager

#if !defined (HTBANotificationManager_) && (INCLUDE_ALL_NotificationManager || defined(INCLUDE_HTBANotificationManager))
#define HTBANotificationManager_

#define RESTRICT_NotificationInterface 1
#define INCLUDE_HTBANotificationInterface 1
#include "NotificationInterface.h"

@protocol JavaUtilMap;

@interface HTBANotificationManager : NSObject < HTBANotificationInterface >

#pragma mark Public

+ (HTBANotificationManager *)defaultManager;

- (void)onReceiveNotificationWithNSString:(NSString *)notificationName
                          withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)postNotificationWithNSString:(NSString *)notificationName
                     withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)registerNotificationWithNSString:(NSString *)notificationName
           withHTBANotificationInterface:(id<HTBANotificationInterface>)obj;

- (void)unregisterNotificationWithNSString:(NSString *)notificationName
             withHTBANotificationInterface:(id<HTBANotificationInterface>)obj;

@end

J2OBJC_EMPTY_STATIC_INIT(HTBANotificationManager)

FOUNDATION_EXPORT HTBANotificationManager *HTBANotificationManager_defaultManager();

J2OBJC_TYPE_LITERAL_HEADER(HTBANotificationManager)

@compatibility_alias ComGithubHowtobuildappLibservicePlatformNotificationManager HTBANotificationManager;

#endif

#pragma pop_macro("INCLUDE_ALL_NotificationManager")
