//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/github/howtobuildapp/libservice/platform/NotificationInterface.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NotificationInterface")
#ifdef RESTRICT_NotificationInterface
#define INCLUDE_ALL_NotificationInterface 0
#else
#define INCLUDE_ALL_NotificationInterface 1
#endif
#undef RESTRICT_NotificationInterface

#if !defined (HTBANotificationInterface_) && (INCLUDE_ALL_NotificationInterface || defined(INCLUDE_HTBANotificationInterface))
#define HTBANotificationInterface_

@protocol JavaUtilMap;

@protocol HTBANotificationInterface < JavaObject >

- (void)onReceiveNotificationWithNSString:(NSString *)notification
                          withJavaUtilMap:(id<JavaUtilMap>)params;

@end

J2OBJC_EMPTY_STATIC_INIT(HTBANotificationInterface)

J2OBJC_TYPE_LITERAL_HEADER(HTBANotificationInterface)

#define ComGithubHowtobuildappLibservicePlatformNotificationInterface HTBANotificationInterface

#endif

#pragma pop_macro("INCLUDE_ALL_NotificationInterface")
