//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/google/gson/internal/bind/ObjectTypeAdapter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ObjectTypeAdapter")
#ifdef RESTRICT_ObjectTypeAdapter
#define INCLUDE_ALL_ObjectTypeAdapter 0
#else
#define INCLUDE_ALL_ObjectTypeAdapter 1
#endif
#undef RESTRICT_ObjectTypeAdapter

#if !defined (GSONObjectTypeAdapter_) && (INCLUDE_ALL_ObjectTypeAdapter || defined(INCLUDE_GSONObjectTypeAdapter))
#define GSONObjectTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_GSONTypeAdapter 1
#include "TypeAdapter.h"

@class GSONGson;
@class GSONJsonReader;
@class GSONJsonWriter;
@protocol GSONTypeAdapterFactory;

/*!
 @brief Adapts types whose static type is only 'Object'.Uses getClass() on
  serialization and a primitive/Map/List on deserialization.
 */
@interface GSONObjectTypeAdapter : GSONTypeAdapter

#pragma mark Public

- (id)readWithGSONJsonReader:(GSONJsonReader *)inArg;

- (void)writeWithGSONJsonWriter:(GSONJsonWriter *)outArg
                         withId:(id)value;

#pragma mark Package-Private

- (instancetype)initWithGSONGson:(GSONGson *)gson;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(GSONObjectTypeAdapter)

inline id<GSONTypeAdapterFactory> GSONObjectTypeAdapter_get_FACTORY();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<GSONTypeAdapterFactory> GSONObjectTypeAdapter_FACTORY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(GSONObjectTypeAdapter, FACTORY, id<GSONTypeAdapterFactory>)

FOUNDATION_EXPORT void GSONObjectTypeAdapter_initWithGSONGson_(GSONObjectTypeAdapter *self, GSONGson *gson);

FOUNDATION_EXPORT GSONObjectTypeAdapter *new_GSONObjectTypeAdapter_initWithGSONGson_(GSONGson *gson) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GSONObjectTypeAdapter *create_GSONObjectTypeAdapter_initWithGSONGson_(GSONGson *gson);

J2OBJC_TYPE_LITERAL_HEADER(GSONObjectTypeAdapter)

@compatibility_alias ComGoogleGsonInternalBindObjectTypeAdapter GSONObjectTypeAdapter;

#endif

#pragma pop_macro("INCLUDE_ALL_ObjectTypeAdapter")
