//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/github/howtobuildapp/libservice/execute/RequestQueue.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RequestQueue")
#ifdef RESTRICT_RequestQueue
#define INCLUDE_ALL_RequestQueue 0
#else
#define INCLUDE_ALL_RequestQueue 1
#endif
#undef RESTRICT_RequestQueue

#if !defined (HTBARequestQueue_) && (INCLUDE_ALL_RequestQueue || defined(INCLUDE_HTBARequestQueue))
#define HTBARequestQueue_

#define RESTRICT_ExecuteInterface 1
#define INCLUDE_HTBAExecuteInterface 1
#include "ExecuteInterface.h"

@class HTBACallback;
@class HTBARequest;

@interface HTBARequestQueue : NSObject < HTBAExecuteInterface >

#pragma mark Public

- (instancetype)init;

- (void)cancelWithId:(id)sender;

- (void)executeRequestWithHTBARequest:(HTBARequest *)req
                               withId:(id)sender
                     withHTBACallback:(HTBACallback *)callback;

- (void)resume;

- (void)setMaxCountWithInt:(jint)maxCount;

- (void)setRealExecutorWithHTBAExecuteInterface:(id<HTBAExecuteInterface>)realExecutor;

- (void)suspend;

@end

J2OBJC_EMPTY_STATIC_INIT(HTBARequestQueue)

FOUNDATION_EXPORT void HTBARequestQueue_init(HTBARequestQueue *self);

FOUNDATION_EXPORT HTBARequestQueue *new_HTBARequestQueue_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT HTBARequestQueue *create_HTBARequestQueue_init();

J2OBJC_TYPE_LITERAL_HEADER(HTBARequestQueue)

@compatibility_alias ComGithubHowtobuildappLibserviceExecuteRequestQueue HTBARequestQueue;

#endif

#pragma pop_macro("INCLUDE_ALL_RequestQueue")
