//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/github/howtobuildapp/libservice/execute/RequestQueueItem.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RequestQueueItem")
#ifdef RESTRICT_RequestQueueItem
#define INCLUDE_ALL_RequestQueueItem 0
#else
#define INCLUDE_ALL_RequestQueueItem 1
#endif
#undef RESTRICT_RequestQueueItem

#if !defined (HTBARequestQueueItem_) && (INCLUDE_ALL_RequestQueueItem || defined(INCLUDE_HTBARequestQueueItem))
#define HTBARequestQueueItem_

@class HTBACallback;
@class HTBARequest;

@interface HTBARequestQueueItem : NSObject

#pragma mark Public

- (instancetype)init;

- (HTBACallback *)getCallback;

- (jlong)getEndTimestamp;

- (jlong)getEnqueueTimestamp;

- (jlong)getRealTime;

- (HTBARequest *)getRequest;

- (id)getSender;

- (jlong)getStartTimestamp;

- (jlong)getTotalTime;

- (jlong)getWaitingTime;

- (void)setCallbackWithHTBACallback:(HTBACallback *)callback;

- (void)setEndTimestampWithLong:(jlong)endTimestamp;

- (void)setEnqueueTimestampWithLong:(jlong)enqueueTimestamp;

- (void)setRequestWithHTBARequest:(HTBARequest *)request;

- (void)setSenderWithId:(id)sender;

- (void)setStartTimestampWithLong:(jlong)startTimestamp;

@end

J2OBJC_EMPTY_STATIC_INIT(HTBARequestQueueItem)

FOUNDATION_EXPORT void HTBARequestQueueItem_init(HTBARequestQueueItem *self);

FOUNDATION_EXPORT HTBARequestQueueItem *new_HTBARequestQueueItem_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT HTBARequestQueueItem *create_HTBARequestQueueItem_init();

J2OBJC_TYPE_LITERAL_HEADER(HTBARequestQueueItem)

@compatibility_alias ComGithubHowtobuildappLibserviceExecuteRequestQueueItem HTBARequestQueueItem;

#endif

#pragma pop_macro("INCLUDE_ALL_RequestQueueItem")
