//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/github/howtobuildapp/libservice/execute/Response.java
//

#include "J2ObjC_source.h"
#include "Response.h"

@interface HTBAResponse () {
 @public
  jint errno__;
  NSString *errmsg_;
  id result_;
}

@end

J2OBJC_FIELD_SETTER(HTBAResponse, errmsg_, NSString *)
J2OBJC_FIELD_SETTER(HTBAResponse, result_, id)

@implementation HTBAResponse

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  HTBAResponse_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (jint)getErrno {
  return errno__;
}

- (void)setErrnoWithInt:(jint)errno_ {
  self->errno__ = errno_;
}

- (NSString *)getErrmsg {
  return errmsg_;
}

- (void)setErrmsgWithNSString:(NSString *)errmsg {
  self->errmsg_ = errmsg;
}

- (id)getResult {
  return result_;
}

- (void)setResultWithId:(id)result {
  self->result_ = result;
}

- (jboolean)isOK {
  return errno__ == 0;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getErrno);
  methods[2].selector = @selector(setErrnoWithInt:);
  methods[3].selector = @selector(getErrmsg);
  methods[4].selector = @selector(setErrmsgWithNSString:);
  methods[5].selector = @selector(getResult);
  methods[6].selector = @selector(setResultWithId:);
  methods[7].selector = @selector(isOK);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "errno__", "I", .constantValue.asLong = 0, 0x2, 6, -1, -1, -1 },
    { "errmsg_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "result_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "setErrno", "I", "setErrmsg", "LNSString;", "setResult", "LNSObject;", "errno" };
  static const J2ObjcClassInfo _HTBAResponse = { "Response", "com.github.howtobuildapp.libservice.execute", ptrTable, methods, fields, 7, 0x401, 8, 3, -1, -1, -1, -1, -1 };
  return &_HTBAResponse;
}

@end

void HTBAResponse_init(HTBAResponse *self) {
  NSObject_init(self);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(HTBAResponse)
