//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/github/howtobuildapp/libservice/storage/StoreKVRequest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_StoreKVRequest")
#ifdef RESTRICT_StoreKVRequest
#define INCLUDE_ALL_StoreKVRequest 0
#else
#define INCLUDE_ALL_StoreKVRequest 1
#endif
#undef RESTRICT_StoreKVRequest

#if !defined (HTBAStoreKVRequest_) && (INCLUDE_ALL_StoreKVRequest || defined(INCLUDE_HTBAStoreKVRequest))
#define HTBAStoreKVRequest_

#define RESTRICT_Request 1
#define INCLUDE_HTBARequest 1
#include "Request.h"

@class HTBAStoreItem;

@interface HTBAStoreKVRequest : HTBARequest

#pragma mark Public

- (instancetype)init;

- (NSString *)getFrom;

- (HTBAStoreItem *)getItem;

- (jint)getOperation;

- (void)setFromWithNSString:(NSString *)from;

- (void)setItemWithHTBAStoreItem:(HTBAStoreItem *)item;

- (void)setOperationWithInt:(jint)operation;

@end

J2OBJC_EMPTY_STATIC_INIT(HTBAStoreKVRequest)

inline jint HTBAStoreKVRequest_get_operationStore();
inline jint HTBAStoreKVRequest_set_operationStore(jint value);
inline jint *HTBAStoreKVRequest_getRef_operationStore();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint HTBAStoreKVRequest_operationStore;
J2OBJC_STATIC_FIELD_PRIMITIVE(HTBAStoreKVRequest, operationStore, jint)

inline jint HTBAStoreKVRequest_get_operationGet();
inline jint HTBAStoreKVRequest_set_operationGet(jint value);
inline jint *HTBAStoreKVRequest_getRef_operationGet();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint HTBAStoreKVRequest_operationGet;
J2OBJC_STATIC_FIELD_PRIMITIVE(HTBAStoreKVRequest, operationGet, jint)

inline jint HTBAStoreKVRequest_get_operationRemove();
inline jint HTBAStoreKVRequest_set_operationRemove(jint value);
inline jint *HTBAStoreKVRequest_getRef_operationRemove();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint HTBAStoreKVRequest_operationRemove;
J2OBJC_STATIC_FIELD_PRIMITIVE(HTBAStoreKVRequest, operationRemove, jint)

inline jint HTBAStoreKVRequest_get_operationRemoveAllExpired();
inline jint HTBAStoreKVRequest_set_operationRemoveAllExpired(jint value);
inline jint *HTBAStoreKVRequest_getRef_operationRemoveAllExpired();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint HTBAStoreKVRequest_operationRemoveAllExpired;
J2OBJC_STATIC_FIELD_PRIMITIVE(HTBAStoreKVRequest, operationRemoveAllExpired, jint)

FOUNDATION_EXPORT void HTBAStoreKVRequest_init(HTBAStoreKVRequest *self);

FOUNDATION_EXPORT HTBAStoreKVRequest *new_HTBAStoreKVRequest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT HTBAStoreKVRequest *create_HTBAStoreKVRequest_init();

J2OBJC_TYPE_LITERAL_HEADER(HTBAStoreKVRequest)

@compatibility_alias ComGithubHowtobuildappLibserviceStorageStoreKVRequest HTBAStoreKVRequest;

#endif

#pragma pop_macro("INCLUDE_ALL_StoreKVRequest")
