//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/github/howtobuildapp/libservice/execute/SyncExecutorManager.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SyncExecutorManager")
#ifdef RESTRICT_SyncExecutorManager
#define INCLUDE_ALL_SyncExecutorManager 0
#else
#define INCLUDE_ALL_SyncExecutorManager 1
#endif
#undef RESTRICT_SyncExecutorManager

#if !defined (HTBASyncExecutorManager_) && (INCLUDE_ALL_SyncExecutorManager || defined(INCLUDE_HTBASyncExecutorManager))
#define HTBASyncExecutorManager_

#define RESTRICT_SyncExecuteInterface 1
#define INCLUDE_HTBASyncExecuteInterface 1
#include "SyncExecuteInterface.h"

@class HTBARequest;
@class HTBAResponse;

@interface HTBASyncExecutorManager : NSObject < HTBASyncExecuteInterface >

#pragma mark Public

+ (HTBASyncExecutorManager *)defaultManager;

- (HTBAResponse *)executeRequestSyncWithHTBARequest:(HTBARequest *)req;

- (void)registerExecutorForKeyWithNSString:(NSString *)key
              withHTBASyncExecuteInterface:(id<HTBASyncExecuteInterface>)executor;

- (void)registerExecutorForRequestWithHTBARequest:(HTBARequest *)req
                     withHTBASyncExecuteInterface:(id<HTBASyncExecuteInterface>)executor;

- (void)unregisterExecutorForKeyWithNSString:(NSString *)key;

- (void)unregisterExecutorForRequestWithHTBARequest:(HTBARequest *)req;

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(HTBASyncExecutorManager)

FOUNDATION_EXPORT void HTBASyncExecutorManager_init(HTBASyncExecutorManager *self);

FOUNDATION_EXPORT HTBASyncExecutorManager *new_HTBASyncExecutorManager_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT HTBASyncExecutorManager *create_HTBASyncExecutorManager_init();

FOUNDATION_EXPORT HTBASyncExecutorManager *HTBASyncExecutorManager_defaultManager();

J2OBJC_TYPE_LITERAL_HEADER(HTBASyncExecutorManager)

@compatibility_alias ComGithubHowtobuildappLibserviceExecuteSyncExecutorManager HTBASyncExecutorManager;

#endif

#pragma pop_macro("INCLUDE_ALL_SyncExecutorManager")
