//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/github/howtobuildapp/libservice/execute/TableInterface.java
//

#include "J2ObjC_source.h"
#include "TableInterface.h"

@interface HTBATableInterface : NSObject

@end

@implementation HTBATableInterface

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "I", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, 2, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, 3, 4, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, 3, 5, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(rowCount);
  methods[1].selector = @selector(columnCount);
  methods[2].selector = @selector(colNameAtWithInt:);
  methods[3].selector = @selector(colDescAtWithInt:);
  methods[4].selector = @selector(valueAtWithInt:withInt:);
  methods[5].selector = @selector(valueAtWithInt:withNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "colNameAt", "I", "colDescAt", "valueAt", "II", "ILNSString;" };
  static const J2ObjcClassInfo _HTBATableInterface = { "TableInterface", "com.github.howtobuildapp.libservice.execute", ptrTable, methods, NULL, 7, 0x609, 6, 0, -1, -1, -1, -1, -1 };
  return &_HTBATableInterface;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(HTBATableInterface)
