//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/github/howtobuildapp/libservice/execute/TableResponse.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TableResponse")
#ifdef RESTRICT_TableResponse
#define INCLUDE_ALL_TableResponse 0
#else
#define INCLUDE_ALL_TableResponse 1
#endif
#undef RESTRICT_TableResponse

#if !defined (HTBATableResponse_) && (INCLUDE_ALL_TableResponse || defined(INCLUDE_HTBATableResponse))
#define HTBATableResponse_

#define RESTRICT_Response 1
#define INCLUDE_HTBAResponse 1
#include "Response.h"

@protocol HTBATableInterface;

@interface HTBATableResponse : HTBAResponse

#pragma mark Public

- (instancetype)init;

- (id<HTBATableInterface>)getTableResult;

@end

J2OBJC_EMPTY_STATIC_INIT(HTBATableResponse)

FOUNDATION_EXPORT void HTBATableResponse_init(HTBATableResponse *self);

FOUNDATION_EXPORT HTBATableResponse *new_HTBATableResponse_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT HTBATableResponse *create_HTBATableResponse_init();

J2OBJC_TYPE_LITERAL_HEADER(HTBATableResponse)

@compatibility_alias ComGithubHowtobuildappLibserviceExecuteTableResponse HTBATableResponse;

#endif

#pragma pop_macro("INCLUDE_ALL_TableResponse")
