//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/github/howtobuildapp/libservice/execute/TableInterface.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TableInterface")
#ifdef RESTRICT_TableInterface
#define INCLUDE_ALL_TableInterface 0
#else
#define INCLUDE_ALL_TableInterface 1
#endif
#undef RESTRICT_TableInterface

#if !defined (HTBATableInterface_) && (INCLUDE_ALL_TableInterface || defined(INCLUDE_HTBATableInterface))
#define HTBATableInterface_

@protocol HTBATableInterface < JavaObject >

- (jint)rowCount;

- (jint)columnCount;

- (NSString *)colNameAtWithInt:(jint)col;

- (NSString *)colDescAtWithInt:(jint)col;

- (NSString *)valueAtWithInt:(jint)row
                     withInt:(jint)col;

- (NSString *)valueAtWithInt:(jint)row
                withNSString:(NSString *)colName;

@end

J2OBJC_EMPTY_STATIC_INIT(HTBATableInterface)

J2OBJC_TYPE_LITERAL_HEADER(HTBATableInterface)

#define ComGithubHowtobuildappLibserviceExecuteTableInterface HTBATableInterface

#endif

#pragma pop_macro("INCLUDE_ALL_TableInterface")
