//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/github/howtobuildapp/libservice/platform/TimerManager.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TimerManager")
#ifdef RESTRICT_TimerManager
#define INCLUDE_ALL_TimerManager 0
#else
#define INCLUDE_ALL_TimerManager 1
#endif
#undef RESTRICT_TimerManager

#if !defined (HTBATimerManager_) && (INCLUDE_ALL_TimerManager || defined(INCLUDE_HTBATimerManager))
#define HTBATimerManager_

@protocol HTBATimerInterface;

@interface HTBATimerManager : NSObject

#pragma mark Public

+ (HTBATimerManager *)defaultManager;

- (void)removeWithHTBATimerInterface:(id<HTBATimerInterface>)target;

- (void)scheduleWithInt:(jint)delay
            withBoolean:(jboolean)repeat
 withHTBATimerInterface:(id<HTBATimerInterface>)target;

- (void)tickFromMainThread;

@end

J2OBJC_EMPTY_STATIC_INIT(HTBATimerManager)

FOUNDATION_EXPORT HTBATimerManager *HTBATimerManager_defaultManager();

J2OBJC_TYPE_LITERAL_HEADER(HTBATimerManager)

@compatibility_alias ComGithubHowtobuildappLibservicePlatformTimerManager HTBATimerManager;

#endif

#pragma pop_macro("INCLUDE_ALL_TimerManager")
