//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/zhangwen/Documents/zwdir/sync/workspace/howtobuildapp/j2objclibios/javasrc/com/github/howtobuildapp/libvm/ViewInterface.java
//

#include "J2ObjC_source.h"
#include "ViewInterface.h"

@interface HTBAViewInterface : NSObject

@end

@implementation HTBAViewInterface

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 2, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 4, 5, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(showLoading);
  methods[1].selector = @selector(hideLoading);
  methods[2].selector = @selector(showHudWithNSString:);
  methods[3].selector = @selector(showAlertWithNSString:withNSString:);
  methods[4].selector = @selector(operationFinishedWithInt:withBoolean:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "showHud", "LNSString;", "showAlert", "LNSString;LNSString;", "operationFinished", "IZ" };
  static const J2ObjcClassInfo _HTBAViewInterface = { "ViewInterface", "com.github.howtobuildapp.libvm", ptrTable, methods, NULL, 7, 0x609, 5, 0, -1, -1, -1, -1, -1 };
  return &_HTBAViewInterface;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(HTBAViewInterface)
